# This script explains how data and code are combined in the GLOBILUC research project. 
# It can also be used to run several scripts

## GEE programmes
#First of all, some data are generated with Google Earth Engine, with different programmes: 
# - prepare_phtf_loss: https://code.earthengine.google.com/c1e0e133f328c877ef5c419118907e6b 
# also available offline at: "code/prepare_phtf_loss_GEE.txt"
# - first_loss_2016_2020: https://code.earthengine.google.com/6fae28fb647bd6adccedfbc83720b5fc
# also available offline at: "code/first_loss_2016_2020_GEE.txt"
# This programme uses data generated by "code/prepare_glass_glc.R" (see below). These data are already loaded in GEE. 

# R programmes
# Install all necessary packages in their project-specific versions. 
source("install_GLOBILUC_packages.R")

# Prepare price time series. This is done first because potential yield GAEZ variables then need to be multiplied by prices in preparation. 
source("code/prepare_prices.R")

# Prepare GAEZ data.This is done first because other data are aligned to the GAEZ resolution and therefore need some GAEZ data template
source("code/prepare_gaez_v3.R")
# Inputs:  - all crop-specific raster zip-folders in "input_data/GAEZ/AES_index_value/Rain-fed/High-input"
# output: - "temp_data/GAEZ/AES_index_value/Rain-fed/high_input_all.tif"

source("code/prepare_gaez_v4.R")
# Inputs:  - all crop-specific raster zip-folders in subfolders of "input_data/GAEZ/v4/AEAY_out_density"
#          - all crop-specific raster zip-folders in subfolders of "input_data/GAEZ/v4/AES_index_value"
# output:  - "temp_data/GAEZ/v4/AEAY_out_density"
#          - "temp_data/GAEZ/v4/AES_index_value"

# Prepare outcome variables (measures of deforestation)
source("code/prepare_glass_glc.R")
# Inputs: - all annual raster layers in "input_data/GLASS-GLC"
#         - "temp_data/GAEZ/AES_index_value/Rain-fed/High-input/Banana.tif"
#         - "input_data/meanFirstLossGlass_maxP" this is an output of own GEE programme. 
# Outputs: - all what is in "temp_data/processed_glass-glc/tropical_aoi"

source("code/prepare_phtfloss.R")
# Inputs: - "input_data/phtfLossSumGlass_maxP" this is an output of own GEE programme. 
#        - "temp_data/GAEZ/AES_index_value/Rain-fed/High-input/Alfalfa.tif"
# Outputs: - all what is in "temp_data/processed_phtfloss/tropical_aoi"

source("code/prepare_loss_drivers.R")
# Inputs: - "input_data/10thLossSumGlass_maxP" this is an output of own GEE programme. 
#         - "input_data/curtis/Goode_FinalClassification_19_05pcnt_prj/Goode_FinalClassification_19_05pcnt_prj.tif"
#        - "temp_data/GAEZ/AES_index_value/Rain-fed/High-input/Alfalfa.tif"
# Outputs: - all what is in "temp_data/processed_lossdrivers/tropical_aoi"

source("code/prepare_pasture2000.R")
# Inputs: - "input_data/CroplandPastureArea2000_Geotiff/Pasture2000_5m.tif" downloaded from http://www.earthstat.org/
#        - "temp_data/GAEZ/AES_index_value/Rain-fed/High-input/Alfalfa.tif"
# Outputs:  - "temp_data/processed_pasture2000/tropical_aoi/pasture_4_driverloss_df.Rdata"




# Merge each outcome variable individual dataset with gaez Agro-Ecological Suitability Index (aesi)
source("code/merge_aesi.R")
# Inputs: - "temp_data/GAEZ/AES_index_value/Rain-fed/high_input_all.tif"
#         - everything in "temp_data/GAEZ/AES_index_value/Rain-fed/High-input"

#         - "temp_data/processed_glass-glc/tropical_aoi/always_zero_mask.tif"
#         - "temp_data/processed_glass-glc/tropical_aoi/ha_first_loss.tif"
#         - "temp_data/processed_glass-glc/tropical_aoi/masked_sbqt_direct_lu.tif"
#         - "temp_data/processed_glass-glc/tropical_aoi/masked_sbqt_mode_lu.tif"

#         - "temp_data/processed_glass-glc/tropical_aoi/always_zero_mask8320.tif"
#         - "temp_data/processed_glass-glc/tropical_aoi/ha_firstloss8320.tif"

#         - "temp_data/processed_phtfloss/tropical_aoi/always_zero_mask_phtfloss.tif"
#         - "temp_data/processed_phtfloss/tropical_aoi/resampled_phtf_loss.tif"

# Outputs:  - "temp_data/GAEZ/AES_index_value/Rain-fed/glass_masked_high_input_all.tif"
#           - "temp_data/merged_datasets/tropical_aoi/glass_aesi_long.Rdata"

#           - "temp_data/GAEZ/AES_index_value/Rain-fed/firstloss8320_masked_high_input_all.tif"
#           - "temp_data/merged_datasets/tropical_aoi/firstloss8320_aesi_long.Rdata"

#           - "temp_data/GAEZ/AES_index_value/Rain-fed/phtfloss_masked_high_input_all.tif"
#           - "temp_data/merged_datasets/tropical_aoi/phtfloss_aesi_long.Rdata"

# Merge each outcome variable individual dataset with gaez Agro-Climatic Achievable Yield (acay)
source("code/merge_aeay.R")
# Inputs: - "temp_data/GAEZ/AES_index_value/Rain-fed/high_input_all.tif"
#         - everything in "temp_data/GAEZ/AES_index_value/Rain-fed/High-input"

#         - "temp_data/processed_glass-glc/tropical_aoi/always_zero_mask.tif"
#         - "temp_data/processed_glass-glc/tropical_aoi/ha_first_loss.tif"
#         - "temp_data/processed_glass-glc/tropical_aoi/masked_sbqt_direct_lu.tif"
#         - "temp_data/processed_glass-glc/tropical_aoi/masked_sbqt_mode_lu.tif"

#         - "temp_data/processed_glass-glc/tropical_aoi/always_zero_mask8320.tif"
#         - "temp_data/processed_glass-glc/tropical_aoi/ha_firstloss8320.tif"

#         - "temp_data/processed_phtfloss/tropical_aoi/always_zero_mask_phtfloss.tif"
#         - "temp_data/processed_phtfloss/tropical_aoi/resampled_phtf_loss.tif"

# Outputs:  - "temp_data/GAEZ/AES_index_value/Rain-fed/glass_masked_high_input_all.tif"
#           - "temp_data/merged_datasets/tropical_aoi/glass_acay_long.Rdata"

#           - "temp_data/GAEZ/AES_index_value/Rain-fed/firstloss8320_masked_high_input_all.tif"
#           - "temp_data/merged_datasets/tropical_aoi/firstloss8320_acay_long.Rdata"

#           - "temp_data/GAEZ/AES_index_value/Rain-fed/phtfloss_masked_high_input_all.tif"
#           - "temp_data/merged_datasets/tropical_aoi/phtfloss_acay_long.Rdata"


# Add country variable and construct standardized suitability indices 
source("code/add_variables.R")
# Inputs: - datasets in "temp_data/merged_datasets/tropical_aoi"
#         - everything in "temp_data/GAEZ/AES_index_value/Rain-fed/High-input"
#         - "input_data/Global_LSIB_Polygons_Detailed"
#         - "temp_data/processed_pasture2000/tropical_aoi/pasture_4_driverloss_df.Rdata"
# Outputs: - "temp_data/merged_datasets/tropical_aoi/glass_aesi_long_final.Rdata"
#          - "temp_data/merged_datasets/tropical_aoi/firstloss8320_aesi_long_final.Rdata"
#          - "temp_data/merged_datasets/tropical_aoi/phtfloss_aesi_long_final.Rdata" 
#          - "temp_data/merged_datasets/tropical_aoi/glass_acay_long_final.Rdata"
#          - "temp_data/merged_datasets/tropical_aoi/firstloss8320_acay_long_final.Rdata"
#          - "temp_data/merged_datasets/tropical_aoi/phtfloss_acay_long_final.Rdata" 



source("code/final_analyses.R")
