# This script explains how data and code are combined in the GLOBILUC research project. 

## GEE programmes
#First of all, some data are generated with Google Earth Engine, with different programmes: 
# - prepare_phtf_loss: https://code.earthengine.google.com/c1e0e133f328c877ef5c419118907e6b 
# also available offline at: "code/prepare_phtf_loss_GEE.txt"
# - first_loss_2016_2020: https://code.earthengine.google.com/6fae28fb647bd6adccedfbc83720b5fc
# also available offline at: "code/first_loss_2016_2020_GEE.txt"
# This programme uses data generated by "code/prepare_glass_glc.R" (see below). These data are already loaded in GEE. 

# R programmes
# Install all necessary packages intheir project-specific versions. 
source("install_GLOBILUC_packages.R")

# Prepare price time series. This is done first because potential yield GAEZ variables then need to be multiplied by prices in preparation. 

# Prepare GAEZ data.This is done first because other data are aligned to the GAEZ resolution and therefore need some GAEZ data template
source("code/prepare_gaez.R")
# Inputs:  - all crop-specific raster zip-folders in "input_data/GAEZ/AES_index_value/Rain-fed/High-input"
# output: - "temp_data/GAEZ/AES_index_value/Rain-fed/high_input_all.tif"

# Prepare outcome variables (measures of deforestation)
source("code/prepare_glass_glc.R")
# Inputs: - all annual raster layers in "input_data/GLASS-GLC"
#         - "temp_data/GAEZ/AES_index_value/Rain-fed/High-input/Banana.tif"
#         - "input_data/meanFirstLossGlass_maxP" this is an output of own GEE programme. 
# Outputs: - all what is in "temp_data/processed_glass-glc/tropical_aoi"

source("code/prepare_phtfloss.R")
#Inputs: - "input_data/phtfLossSumGlass_maxP" this is an output of own GEE programme. 
#        - "temp_data/GAEZ/AES_index_value/Rain-fed/High-input/Alfalfa.tif"
# Outputs: - all what is in "temp_data/processed_phtfloss/tropical_aoi"

# Merge each outcome variable individual dataset with gaez
source("code/merge.R")
# Inputs: - "temp_data/GAEZ/AES_index_value/Rain-fed/high_input_all.tif"
#         - everything in "temp_data/GAEZ/AES_index_value/Rain-fed/High-input"

#         - "temp_data/processed_glass-glc/tropical_aoi/always_zero_mask.tif"
#         - "temp_data/processed_glass-glc/tropical_aoi/masked_first_loss.tif"
#         - "temp_data/processed_glass-glc/tropical_aoi/masked_sbqt_direct_lu.tif"
#         - "temp_data/processed_glass-glc/tropical_aoi/masked_sbqt_mode_lu.tif"

#         - "temp_data/processed_glass-glc/tropical_aoi/always_zero_mask8320.tif"
#         - "temp_data/processed_glass-glc/tropical_aoi/masked_firstloss8320.tif"

#         - "temp_data/processed_phtfloss/tropical_aoi/always_zero_mask_phtfloss.tif"
#         - "temp_data/processed_phtfloss/tropical_aoi/resampled_phtf_loss.tif"

# Outputs:  - "temp_data/GAEZ/AES_index_value/Rain-fed/glass_masked_high_input_all.tif"
#           - "temp_data/merged_datasets/tropical_aoi/glass_gaez_long.Rdata"

#           - "temp_data/GAEZ/AES_index_value/Rain-fed/firstloss8320_masked_high_input_all.tif"
#           - "temp_data/merged_datasets/tropical_aoi/firstloss8320_gaez_long.Rdata"

#           - "temp_data/GAEZ/AES_index_value/Rain-fed/phtfloss_masked_high_input_all.tif"
#           - "temp_data/merged_datasets/tropical_aoi/phtfloss_gaez_long.Rdata"


# Add country variable and construct standardized suitability indices 
source("code/add_variables.R")
# Inputs: - datasets in "temp_data/merged_datasets/tropical_aoi"
#         - everything in "temp_data/GAEZ/AES_index_value/Rain-fed/High-input"
#         - "input_data/Global_LSIB_Polygons_Detailed"
# Outputs: - "temp_data/merged_datasets/tropical_aoi/glass_gaez_long_final.Rdata"
#          - "temp_data/merged_datasets/tropical_aoi/firstloss8320_gaez_long_final.Rdata"
#          - "temp_data/merged_datasets/tropical_aoi/phtfloss_gaez_long_final.Rdata" 


